import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";

import type { AppState, AppThunk } from "../../app/store";
import type { Food, Recipe } from "../../lib/models";
import { getFood, updateFood } from "./foodAPI";
import { getPublicRecipes, postRecipe } from "./recipeAPI";

export interface FoodState {
  inventory: Food[];
  status: "idle" | "loading" | "failed";
}

const initialState: FoodState = {
  inventory: [],
  status: "idle",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getFoodAsync = createAsyncThunk(
  "food/getFood",
  async (arg, thunkAPI) => {
    const response = await getFood();

    return response.data;
  }
);

export const updateFoodAsync = createAsyncThunk(
  "food/updateFood",
  async (arg: Food[], thunkAPI) => {
    const response = await updateFood(arg);
    // thunkAPI.dispatch(getFoodAsync());

    return response.data;
  }
);

export const foodSlice = createSlice({
  name: "food",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // updateFood: (state, action: PayloadAction<Food[]>) => {
    //   // Redux Toolkit allows us to write "mutating" logic in reducers. It
    //   // doesn't actually mutate the state because it uses the Immer library,
    //   // which detects changes to a "draft state" and produces a brand new
    //   // immutable state based off those changes
    //   state.inventory = action.payload;
    //   // while (state.buffer.length > state.bufferSize) {
    //   //   state.buffer.pop();
    //   // }
    // },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getFoodAsync.pending, (state, action) => {
        state.status = "loading";
      })
      .addCase(getFoodAsync.fulfilled, (state, action) => {
        state.status = "idle";
        if (action.payload) state.inventory = action.payload;
      })
      .addCase(updateFoodAsync.pending, (state, action) => {
        state.status = "loading";
      })
      .addCase(updateFoodAsync.fulfilled, (state, action) => {
        state.status = "idle";
        if (action.payload) state.inventory = action.payload;
      });
  },
});

// export const { updateFood } = foodSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectFood = (state: AppState) => state.food.inventory;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (id: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectUserName(getState());
//     if (currentValue % 2 === 1) {
//       dispatch(getNameAsync(id));
//     }
//   };

export default foodSlice.reducer;
