import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { getSession } from "next-auth/react";

import type { AppState, AppThunk } from "../../app/store";
import { fetchUserByEmail } from "./userAPI";

export interface UserState {
  id: string | null;
  status: "idle" | "loading" | "failed";
}

const initialState: UserState = {
  id: null,
  status: "idle",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getUserIdAsync = createAsyncThunk("user/fetchUserId", async () => {
  const {
    user: { email },
  } = await getSession();

  const res = await fetchUserByEmail(email);
  // The value we return becomes the `fulfilled` action payload

  const id: string =
    typeof res.data._id !== "string" ? res.data._id.toString() : res.data._id;

  // console.log(id);
  return id;
});

export const userSlice = createSlice({
  name: "user",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setId: (state, action: PayloadAction<string>) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.id = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getUserIdAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(getUserIdAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.id = action.payload;
      });
  },
});

export const { setId } = userSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectUserId = (state: AppState) => state.user.id;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (id: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectUserName(getState())
//     if (currentValue % 2 === 1) {
//       dispatch(getNameAsync(id))
//     }
//   }

export default userSlice.reducer;
