import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'

import type { AppState, AppThunk } from '../../app/store'
import { fetchUser } from './userAPI'

export interface UserState {
  name: string
  status: 'idle' | 'loading' | 'failed'
}

const initialState: UserState = {
  name: '',
  status: 'idle',
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getNameAsync = createAsyncThunk(
  'user/fetchUser',
  async (id: number) => {
    const response = await fetchUser(id)
    // The value we return becomes the `fulfilled` action payload
    return response.data
  }
)

export const userSlice = createSlice({
  name: 'user',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setName: (state, action: PayloadAction<string>) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.name = action.payload
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getNameAsync.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(getNameAsync.fulfilled, (state, action) => {
        state.status = 'idle'
        state.name = action.payload
      })
  },
})

export const { setName } = userSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectUserName = (state: AppState) => state.user.name

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
export const incrementIfOdd =
  (id: number): AppThunk =>
  (dispatch, getState) => {
    const currentValue = selectUserName(getState())
    if (currentValue % 2 === 1) {
      dispatch(getNameAsync(id))
    }
  }

export default userSlice.reducer